### ISSUE TITLE
[crash on start] doesnt work on 1.19.2

### ISSUE THREAD

**Issue by Xplodin** [ianm1647/everlasting-abilities-compat#1]
[crash-2023-04-26_07.40.32-fml.txt](https://github.com/ianm1647/everlasting-abilities-compat/files/11332358/crash-2023-04-26_07.40.32-fml.txt)

**Comment by D3SL** [comment]
Author commented on curseforge that this is due to everlasting abilities main getting overhauled to rely on datapacks, leaving everlasting abilities compat incompatible since it's a full on java mod.

**Comment by Xplodin** [comment]
ahh dang. I hope there will be a datapack at least. :) This mod seems dope

**Comment by ianm1647** [comment]
> ahh dang. I hope there will be a datapack at least. :) This mod seems dope

all you have to do is download a version before 2.0.0 for the mod to work
